<?php

declare(strict_types=1);

namespace LiquidRazor\DtoApiBundle\OpenApi\TypeScript;

use JsonException;

use function in_array;
use function is_array;
use function is_bool;
use function is_int;
use function is_string;
use function preg_match;
use function sprintf;
use function str_contains;

/**
 * Turns an OpenAPI document's `components.schemas` into TypeScript type aliases.
 *
 * Framework-free and side-effect-free: feed it the array returned by
 * {@see \LiquidRazor\DtoApiBundle\OpenApi\OpenApiBuilder::build()} and it returns
 * the `.ts` source as a string. The caller decides what to do with it (write to
 * disk, print, diff).
 *
 * One `export type {SchemaName} = …;` is emitted per schema, in document order.
 * The type mapping follows what {@see \LiquidRazor\DtoApiBundle\OpenApi\Schema\DtoSchemaFactory}
 * actually emits — scalars, arrays (`items.type` / `items.$ref`), `$ref`,
 * 3.1 nullable unions (`type: ['null', X]`) and the `nullable: true` fallback,
 * enums, and the `type: object` catch-all.
 */
final readonly class TsTypeGenerator
{
    private const string HEADER = <<<'TS'
        /* eslint-disable */
        /**
         * AUTO-GENERATED by `bin/console dto-api:generate:ts-types` — do not edit by hand.
         * Source: OpenAPI components.schemas (LiquidRazor DtoApiBundle).
         */
        TS;

    /**
     * @param array<string, mixed> $openApi             the full document from OpenApiBuilder::build()
     * @param string|null          $nullableWrapper     wrap nullable types as `Wrapper<T>` instead of `T | null` (e.g. `Option`); null keeps the union form
     * @param string|null          $nullableWrapperImport module to `import type { Wrapper } from …` (emitted only when the wrapper is used)
     *
     * @throws JsonException
     */
    public function generate(array $openApi, ?string $nullableWrapper = null, ?string $nullableWrapperImport = null): string
    {
        // The builder mixes arrays and stdClass (paths/schemas are objectified at
        // different depths). Round-trip through JSON to a pure nested-array form
        // so the walk below never has to care which it got.
        /** @var array<string, mixed> $doc */
        $doc = json_decode(json_encode($openApi, JSON_THROW_ON_ERROR), true, 512, JSON_THROW_ON_ERROR);

        /** @var array<string, mixed> $schemas */
        $schemas = $doc['components']['schemas'] ?? [];

        $blocks = [];
        foreach ($schemas as $name => $schema) {
            if (!is_array($schema)) {
                continue;
            }
            $blocks[] = $this->renderType((string) $name, $schema, $nullableWrapper);
        }

        $body = implode("\n\n", $blocks);

        $header = self::HEADER;
        // Only import the wrapper when something actually used it, so the output
        // never carries an unused import (which eslint would flag).
        if (null !== $nullableWrapper && null !== $nullableWrapperImport && str_contains($body, $nullableWrapper . '<')) {
            $header .= sprintf("\n\nimport type { %s } from '%s';", $nullableWrapper, $nullableWrapperImport);
        }

        return $header . "\n\n" . $body . "\n";
    }

    /**
     * @param array<string, mixed> $schema
     */
    private function renderType(string $name, array $schema, ?string $nullableWrapper): string
    {
        // Top-level DTO schemas are objects with a `properties` map; anything else
        // (a bare enum, a scalar) becomes a simple alias.
        $properties = $schema['properties'] ?? null;
        if (!is_array($properties)) {
            return sprintf('export type %s = %s;', $name, $this->tsType($schema, $nullableWrapper));
        }

        /** @var list<string> $required */
        $required = is_array($schema['required'] ?? null) ? $schema['required'] : [];

        $lines = [];
        foreach ($properties as $key => $propSchema) {
            if (!is_array($propSchema)) {
                continue;
            }
            $optional = in_array((string) $key, $required, true) ? '' : '?';
            $lines[] = sprintf('    %s%s: %s;', $this->propertyKey((string) $key), $optional, $this->tsType($propSchema, $nullableWrapper));
        }

        if ($lines === []) {
            return sprintf('export type %s = Record<string, never>;', $name);
        }

        return sprintf("export type %s = {\n%s\n};", $name, implode("\n", $lines));
    }

    /**
     * Map a single JSON-Schema node to a TS type expression.
     *
     * @param array<string, mixed> $node
     */
    private function tsType(array $node, ?string $nullableWrapper): string
    {
        // $ref always wins — point at the referenced type name.
        if (isset($node['$ref']) && is_string($node['$ref'])) {
            return $this->refName($node['$ref']);
        }

        [$type, $nullable] = $this->normaliseType($node);
        if (($node['nullable'] ?? null) === true) {
            $nullable = true;
        }

        $base = $this->baseType($type, $node, $nullableWrapper);

        if (!$nullable) {
            return $base;
        }

        return null !== $nullableWrapper ? sprintf('%s<%s>', $nullableWrapper, $base) : $base . ' | null';
    }

    /**
     * Resolve the OpenAPI `type` keyword, accounting for the 3.1 nullable union
     * form `type: ['null', 'string']`.
     *
     * @param array<string, mixed> $node
     *
     * @return array{0: string|null, 1: bool} [resolvedType, nullable]
     */
    private function normaliseType(array $node): array
    {
        $type = $node['type'] ?? null;

        if (is_array($type)) {
            $nullable = in_array('null', $type, true);
            $remaining = array_values(array_filter($type, static fn ($t): bool => $t !== 'null'));

            return [$remaining[0] ?? null, $nullable];
        }

        return [is_string($type) ? $type : null, false];
    }

    /**
     * @param array<string, mixed> $node
     */
    private function baseType(?string $type, array $node, ?string $nullableWrapper): string
    {
        // Enums short-circuit the scalar mapping: emit a literal union.
        if (isset($node['enum']) && is_array($node['enum']) && $node['enum'] !== []) {
            return $this->enumUnion($node['enum']);
        }

        return match ($type) {
            'string' => 'string',
            'integer', 'number' => 'number',
            'boolean' => 'boolean',
            'array' => $this->arrayType($node, $nullableWrapper),
            'object' => $this->objectType($node, $nullableWrapper),
            default => 'unknown',
        };
    }

    /**
     * @param array<string, mixed> $node
     */
    private function arrayType(array $node, ?string $nullableWrapper): string
    {
        $items = $node['items'] ?? null;
        if (!is_array($items)) {
            return 'unknown[]';
        }

        $itemType = $this->tsType($items, $nullableWrapper);

        // Parenthesise unions so `(A | null)[]` keeps its meaning.
        return preg_match('/[ |]/', $itemType) ? sprintf('(%s)[]', $itemType) : $itemType . '[]';
    }

    /**
     * @param array<string, mixed> $node
     */
    private function objectType(array $node, ?string $nullableWrapper): string
    {
        // An object with declared properties is an inline shape; the bare
        // `type: object` fallback (no properties) becomes an index signature.
        if (isset($node['properties']) && is_array($node['properties']) && $node['properties'] !== []) {
            /** @var list<string> $required */
            $required = is_array($node['required'] ?? null) ? $node['required'] : [];

            $parts = [];
            foreach ($node['properties'] as $key => $propSchema) {
                if (!is_array($propSchema)) {
                    continue;
                }
                $optional = in_array((string) $key, $required, true) ? '' : '?';
                $parts[] = sprintf('%s%s: %s', $this->propertyKey((string) $key), $optional, $this->tsType($propSchema, $nullableWrapper));
            }

            return $parts === [] ? 'Record<string, unknown>' : '{ ' . implode('; ', $parts) . ' }';
        }

        return 'Record<string, unknown>';
    }

    /**
     * @param list<mixed> $values
     */
    private function enumUnion(array $values): string
    {
        $literals = [];
        foreach ($values as $value) {
            $literals[] = match (true) {
                is_string($value) => "'" . str_replace("'", "\\'", $value) . "'",
                is_bool($value) => $value ? 'true' : 'false',
                is_int($value) || is_float($value) => (string) $value,
                $value === null => 'null',
                default => 'unknown',
            };
        }

        return implode(' | ', array_values(array_unique($literals)));
    }

    private function refName(string $ref): string
    {
        $parts = explode('/', $ref);

        return end($parts) ?: 'unknown';
    }

    /**
     * Quote keys that are not bare TS identifiers (e.g. snake/kebab wire names).
     */
    private function propertyKey(string $key): string
    {
        return preg_match('/^[A-Za-z_$][A-Za-z0-9_$]*$/', $key) === 1
            ? $key
            : "'" . str_replace("'", "\\'", $key) . "'";
    }
}
